// <auto-generated />
using System;
using Benivo.Demo.DAL.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Benivo.Demo.DAL.Migrations
{
    [DbContext(typeof(BenivoDbContext))]
    [Migration("20211118164411_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Cities_Id")
                        .IsClustered();

                    b.HasIndex("CountryId");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique()
                        .HasDatabaseName("UK_Cities_NameCountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Companies_Id")
                        .IsClustered();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UK_Companies_Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.Country", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Countries_Id")
                        .IsClustered();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UK_Countries_Name");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.EmploymentType", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_EmployementTypes")
                        .IsClustered();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UK_EmployementTypes_Name");

                    b.ToTable("EmployementTypes");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.JobAnnouncement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("EmploymentTypeId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("JobCategoryId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_JobAnnouncements_Id")
                        .IsClustered();

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("JobCategoryId");

                    b.ToTable("JobAnnouncements");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.JobCategory", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<short?>("ParentId")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK_JobCategories_Id")
                        .IsClustered();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UK_JobCategories_Name");

                    b.HasIndex("ParentId");

                    b.ToTable("JobCategories");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Users_Id")
                        .IsClustered();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_Users_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UK_Users_Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.UserJobAnnouncement", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("JobAnnouncementId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsBookmarked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId", "JobAnnouncementId")
                        .HasName("PK_UserJobAnnouncements_UserId_JobAnnouncementId")
                        .IsClustered();

                    b.HasIndex("JobAnnouncementId");

                    b.ToTable("UserJobAnnouncements");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.City", b =>
                {
                    b.HasOne("Benivo.Demo.Entities.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_Cities_Countries_CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.JobAnnouncement", b =>
                {
                    b.HasOne("Benivo.Demo.Entities.Entities.City", "City")
                        .WithMany("JobAnnouncements")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_JobAnnouncements_Cities_CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Benivo.Demo.Entities.Entities.Company", "Company")
                        .WithMany("JobAnnouncements")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_JobAnnouncements_Company_CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Benivo.Demo.Entities.Entities.EmploymentType", "EmploymentType")
                        .WithMany("JobAnnouncements")
                        .HasForeignKey("EmploymentTypeId")
                        .HasConstraintName("FK_JobAnnouncements_EmployementTypes_EmployementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Benivo.Demo.Entities.Entities.JobCategory", "JobCategory")
                        .WithMany("JobAnnouncements")
                        .HasForeignKey("JobCategoryId")
                        .HasConstraintName("FK_JobAnnouncements_JobCategories_JobCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Company");

                    b.Navigation("EmploymentType");

                    b.Navigation("JobCategory");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.JobCategory", b =>
                {
                    b.HasOne("Benivo.Demo.Entities.Entities.JobCategory", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_JobCategories_JobCategories_ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.UserJobAnnouncement", b =>
                {
                    b.HasOne("Benivo.Demo.Entities.Entities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("UserJobAnnouncements")
                        .HasForeignKey("JobAnnouncementId")
                        .HasConstraintName("FK_UserJobAnnouncements_JobAnnouncements_JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Benivo.Demo.Entities.Entities.User", "User")
                        .WithMany("UserJobAnnouncements")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserJobAnnouncements_User_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobAnnouncement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.City", b =>
                {
                    b.Navigation("JobAnnouncements");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.Company", b =>
                {
                    b.Navigation("JobAnnouncements");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.EmploymentType", b =>
                {
                    b.Navigation("JobAnnouncements");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.JobAnnouncement", b =>
                {
                    b.Navigation("UserJobAnnouncements");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.JobCategory", b =>
                {
                    b.Navigation("JobAnnouncements");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Benivo.Demo.Entities.Entities.User", b =>
                {
                    b.Navigation("UserJobAnnouncements");
                });
#pragma warning restore 612, 618
        }
    }
}
